[package]
name = "szmer"
version = "0.1.0"
edition = "2021"

[dependencies]
notify-rust = "4.11.7"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dialoguer = "0.11"
rand = "0.8"
chrono = "0.4"
